title: Products

icon: 📜

options:
  url: false
  status: false
  delete: false

tabs:

  # Subpages tab with pages section
  subpages:
    label: Subpages
    icon: page
    # preset: pages

    sections:
      products:
        headline: Products
        type: pages
        status: all
        templates: product

    # drafts:
    #   extends: sections/products
    #   headline: Unpublished products

    # unlisted:
    #   extends: sections/products
    #   headline: Products in review

    # listed:
    #   extends: sections/products
    #   headline: Published products
  # Seo Tab with a fields section
  seo:
    label: Catalog Sync
    icon: refresh
    sections:
      # seo fields
      seo:
        type: fields
        fields:
          kc-products-sync:
            type: products-sync
          metaTitle:
            label: Meta Title
            type: text
          metaDescription:
            label: Meta Description
            type: textarea