title: Site

sections:
  # the form for the page
  content:
    type: fields
    fields:
      headline:
        label: Headline
        type: text
        required: true
        minLength: 10
        maxLength: 20
        width: 3/4
      year:
        label: Year
        type: number
        min: 2000
        required: true
        width: 1/4
      currency:
        label: Budget
        type: currency
        message: hi
      link:
        label: Link
        type: url
      tags:
        label: Tags
        type: tags
      text:
        label: Text
        type: textarea
        minLength: 10
  projects:
    headline: Projects
    type: pages
    query: site.find("projects").children.visible
    layout: list
    item:
      info: "{{ page.year }}"
    create: project

  blog:
    headline: Blog
    type: pages
    query: site.find('blog').children.visible
    layout: list
    item:
      info: "{{ page.date('d.m.Y') }}"
    create: article

  about:
    headline: About
    type: pages
    query: site.find('about').children
    layout: list
    item:
      info: "{{ page.position }}"
    create: team

